version: 2
updates:
    - package-ecosystem: "github-actions"
      target-branch: "develop"
      directory: "/"
      schedule:
          interval: "monthly"
      commit-message:
          prefix: "ci"
    - package-ecosystem: "npm"
      target-branch: "develop"
      directory: "/"
      schedule:
          interval: "monthly"
      versioning-strategy: "increase"
      ignore:
          - dependency-name: "*"
            update-types: ["version-update:semver-patch"]
      commit-message:
          prefix: "fix"
          prefix-development: "chore"
          include: "scope"
    - package-ecosystem: "npm"
      target-branch: "develop"
      directory: "/backend"
      schedule:
          interval: "monthly"
      versioning-strategy: "increase"
      ignore:
          - dependency-name: "*"
            update-types: ["version-update:semver-patch"]
      commit-message:
          prefix: "fix"
          prefix-development: "chore"
          include: "scope"
    - package-ecosystem: "npm"
      target-branch: "develop"
      directory: "/frontend"
      schedule:
          interval: "monthly"
      versioning-strategy: "increase"
      ignore:
          - dependency-name: "*"
            update-types: ["version-update:semver-patch"]
      commit-message:
          prefix: "fix"
          prefix-development: "chore"
          include: "scope"
