services:
    database:
        image: postgres:10.14
        environment:
            - POSTGRES_DB=${TYPEORM_DATABASE}
            - POSTGRES_USER=${TYPEORM_USERNAME}
            - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
        ports:
            - 5432:5432
