name: Integration
on: [push]
env:
    NODE_VERSION: "14.18.3"
    NODE_DEPENDENCY_LOCK_ROOT: "package-lock.json"
    NODE_DEPENDENCY_LOCK_BACKEND: "backend/package-lock.json"
    NODE_DEPENDENCY_LOCK_FRONTEND: "frontend/package-lock.json"
jobs:
    install-root:
        name: Install Root
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_ROOT }}
            - run: node --version
            - run: npm --version
            - run: npm install
    install-backend:
        name: Install Backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_BACKEND }}
            - run: cd backend && npm install
    install-frontend:
        name: Install Frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_FRONTEND }}
            - run: cd frontend && npm install
    format:
        name: Format
        needs: install-root
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_ROOT }}
            - run: npm run format
    lint-backend:
        name: Lint Backend
        needs: install-backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_BACKEND }}
            - run: cd backend && npm run lint
    lint-frontend:
        name: Lint Frontend
        needs: install-frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_FRONTEND }}
            - run: cd frontend && npm run lint
    test-backend:
        name: Test Backend
        needs: install-backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_BACKEND }}
            - run: cd backend && npm run test
    test-frontend:
        name: Test Frontend
        needs: install-frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_FRONTEND }}
            - run: cd frontend && npm run test
    release:
        name: Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        needs: [format, lint-backend, lint-frontend, test-backend, test-frontend]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ NODE_VERSION }}
                  cache: "npm"
                  cache-dependency-path: ${{ NODE_DEPENDENCY_LOCK_ROOT }}
            - run: npm run release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
