name: Integration
on: [push]
env:
    NODE_VERSION: 14.18.3
jobs:
    install-root:
        name: Install Root
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: node_modules
                  key: ${{ hashFiles('package-lock.json') }}
            - run: node --version
            - run: npm --version
            - run: npm install
    install-backend:
        name: Install Backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: backend/node_modules
                  key: ${{ hashFiles('backend/package-lock.json') }}
            - run: cd backend && npm install
    install-frontend:
        name: Install Frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: frontend/node_modules
                  key: ${{ hashFiles('frontend/package-lock.json') }}
            - run: cd frontend && npm install
    format:
        name: Format
        needs: install-root
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: node_modules
                  key: ${{ hashFiles('package-lock.json') }}
            - run: npm run format
    lint-backend:
        name: Lint Backend
        needs: install-backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: backend/node_modules
                  key: ${{ hashFiles('backend/package-lock.json') }}
            - run: cd backend && npm run lint
    lint-frontend:
        name: Lint Frontend
        needs: install-frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: frontend/node_modules
                  key: ${{ hashFiles('frontend/package-lock.json') }}
            - run: cd frontend && npm run lint
    test-backend:
        name: Test Backend
        needs: install-backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: backend/node_modules
                  key: ${{ hashFiles('backend/package-lock.json') }}
            - run: cd backend && npm run test
    test-frontend:
        name: Test Frontend
        needs: install-frontend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: frontend/node_modules
                  key: ${{ hashFiles('frontend/package-lock.json') }}
            - run: cd frontend && npm run test
    release:
        name: Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        needs: [format, lint-backend, lint-frontend, test-backend, test-frontend]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - uses: actions/cache@v3.0.8
              with:
                  path: node_modules
                  key: ${{ hashFiles('package-lock.json') }}
            - run: npm run release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
